#!/usr/bin/env bash

if [[ "$1" = "-h" ]]; then
    echo "Usage: docker-push [tag]"
    echo
    echo "  tag defaults to 'dev'"
    exit 1
fi

tag=${1:-dev}

images=(
    maxhollmann/podify-base
    maxhollmann/podify-web
    maxhollmann/podify-worker
)

for image in ${images[@]}; do
    echo "Tagging $image:dev as $image:$tag"
    docker tag $image:dev $image:$tag
done

for image in ${images[@]}; do
    echo "Pushing $image:$tag"
    docker push $image:$tag
done
